services:

  www:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./data:/var/www/data
    ports:
      - 80:80
      - 443:443
    networks:
      - network

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: fieldday
      MYSQL_USER: webuser
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - network

networks:
  network:
    driver: bridge